language: r

r:

before_install: R -e 'source("https://install-github.me/r-lib/remotes")'

env:
 - TRAVIS_R_VERSION="3.2.0"

r_packages:
- dplyr
- magrittr
- purrr
- stringr
- testthat
- tibble

script:
 - Rscript -e 'testthat::test_dir("./tests/", stop_on_failure = TRUE)'
